<?php
session_start(); include "includes/db.php"; include "includes/model.php"; requireLogin();
$store=mysqli_fetch_assoc(mysqli_query($conn,"SELECT * FROM store_profile WHERE id=1"));
$r=mysqli_query($conn,"SELECT p.*, s.demand_index FROM products p JOIN store_profile s ON p.store_id=s.id");
$products=[];$total_stock=0;$high=0;$over=0;$waste=0;$disc=0;$weekly=0;
while($p=mysqli_fetch_assoc($r)){ $forecast=forecastDemand($p["base_daily_sales"],$p["category"],$p["demand_index"],$p["promotion_flag"],$p["days_to_expiry"]); mysqli_query($conn,"UPDATE products SET predicted_demand=$forecast WHERE id=".$p["id"]); $risk=riskLevel($p["current_stock"],$forecast,$p["days_to_expiry"]); $d=discountValue($risk,$p["days_to_expiry"]); $p["forecast"]=$forecast;$p["risk"]=$risk;$p["discount"]=$d;$products[]=$p; $total_stock+=$p["current_stock"];$weekly+=$forecast;if($risk=="High"){$high++;$waste+=$p["current_stock"]*$p["unit_price"];} if($p["current_stock"]>=$forecast*1.4)$over++; $disc+=$d; }
$count=count($products);$avg=$count?round($disc/$count):0;
?><!DOCTYPE html><html><head><title>Dashboard</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="layout"><?php include "includes/sidebar.php"; ?><main class="main">
<div class="page-title"><h1>Dashboard</h1><p><?= $store["store_name"] ?> — <?= $store["suburb"] ?></p></div>
<div class="note"><strong>Customer Forecast:</strong> Average daily customers last month: <?= number_format($store["avg_daily_customers_last_month"]) ?>. Predicted average daily customers next month: <?= number_format($store["predicted_daily_customers_next_month"]) ?>.</div>
<div class="grid grid-4"><div class="card stat"><h3>Total Products</h3><strong><?= $count ?></strong><p>Active inventory</p></div><div class="card stat"><h3>Total Stock</h3><strong><?= number_format($total_stock) ?></strong><p>Units in store</p></div><div class="card stat"><h3>High Risk Items</h3><strong><?= $high ?></strong><p>Need action</p></div><div class="card stat"><h3>Overstocked</h3><strong><?= $over ?></strong><p>Stock above forecast</p></div></div><br>
<div class="grid grid-3"><div class="card stat"><h3>Estimated Waste Value</h3><strong>$<?= number_format($waste,2) ?></strong></div><div class="card stat"><h3>Avg AI Discount</h3><strong><?= $avg ?>%</strong></div><div class="card stat"><h3>Weekly Forecast Demand</h3><strong><?= number_format($weekly) ?></strong></div></div><br>
<div class="grid grid-2"><div class="card"><h2>AI Quick Recommendations</h2><br><?php foreach($products as $p){ if($p["risk"]=="High") echo "<div class='card alert-card'><strong>{$p["product_name"]}</strong><p>Forecast: {$p["forecast"]} • Stock: {$p["current_stock"]} • ".aiAction($p["risk"],$p["discount"])."</p></div>"; } ?></div><div class="card"><h2>Customer Trend: Past vs Future Month</h2><div class="chart-box"><?php $cf=mysqli_query($conn,"SELECT * FROM customer_forecast"); while($c=mysqli_fetch_assoc($cf)){ $h1=round($c["past_month_customers"]/120); $h2=round($c["predicted_next_month_customers"]/120); echo "<div class='bar' style='height:{$h1}px;background:#2563eb'>{$c["week_label"]}<br>Past</div><div class='bar' style='height:{$h2}px;background:#0f7a4f'>{$c["week_label"]}<br>Future</div>"; } ?></div></div></div>
</main></div></body></html>