<?php
session_start(); include "includes/db.php"; include "includes/model.php"; requireLogin(); requirePermission("can_view_reports");

if(isset($_POST["generate_report"])){
    $gen_by = mysqli_real_escape_string($conn, $_SESSION["name"]);
    $recipients = [];
    $rr = mysqli_query($conn,"SELECT * FROM report_recipients WHERE status='Active'");
    while($x=mysqli_fetch_assoc($rr)){ $recipients[] = $x["email"]; }

    $r=mysqli_query($conn,"SELECT p.*,s.demand_index FROM products p JOIN store_profile s ON p.store_id=s.id");
    $high=0;$medium=0;$value=0;
    while($p=mysqli_fetch_assoc($r)){
        $forecast=forecastDemand($p["base_daily_sales"],$p["category"],$p["demand_index"],$p["promotion_flag"],$p["days_to_expiry"]);
        $risk=riskLevel($p["current_stock"],$forecast,$p["days_to_expiry"]);
        if($risk=="High"){ $high++; $value += $p["current_stock"]*$p["unit_price"]; }
        if($risk=="Medium") $medium++;
    }
    $summary = mysqli_real_escape_string($conn, implode(", ", $recipients));
    mysqli_query($conn,"INSERT INTO report_history(report_type,generated_by,recipient_summary,high_risk_count,medium_risk_count,potential_waste_value,status) VALUES('Daily Automated Report','$gen_by','$summary',$high,$medium,$value,'Generated & Ready to Email')");
    header("Location: reports.php?generated=1"); exit();
}

$r=mysqli_query($conn,"SELECT p.*,s.demand_index FROM products p JOIN store_profile s ON p.store_id=s.id");
$value=0;$counts=["High"=>0,"Medium"=>0,"Low"=>0];$dp=0;$ds=0;$cat=[];
while($p=mysqli_fetch_assoc($r)){
    $forecast=forecastDemand($p["base_daily_sales"],$p["category"],$p["demand_index"],$p["promotion_flag"],$p["days_to_expiry"]);
    $risk=riskLevel($p["current_stock"],$forecast,$p["days_to_expiry"]);
    $disc=discountValue($risk,$p["days_to_expiry"]);
    $counts[$risk]++;
    if(!isset($cat[$p["category"]])) $cat[$p["category"]] = 0;
    $cat[$p["category"]] += $forecast;
    if($risk=="High") $value += $p["current_stock"]*$p["unit_price"];
    if($disc>0) $dp++;
    $ds += $disc;
}
$total=array_sum($counts);$avg=$total?round($ds/$total):0;$savings=$value*($avg/100);
$history=mysqli_query($conn,"SELECT * FROM report_history ORDER BY created_at DESC LIMIT 8");
$rec=mysqli_query($conn,"SELECT * FROM report_recipients WHERE status='Active'");
?><!DOCTYPE html><html><head><title>Reports</title><link rel="stylesheet" href="assets/style.css"></head><body><div class="layout"><?php include "includes/sidebar.php"; ?><main class="main">
<div class="page-title"><h1>Daily Reports</h1><p>FreshGuard Supermarket automated reporting, PDF export and email delivery workflow</p></div>

<div class="report-actions no-print">
<form method="POST" style="display:inline;"><button name="generate_report">Generate Today’s Report</button></form>
<button class="btn btn-blue" onclick="window.print()">Export / Save as PDF</button>
<a class="btn btn-light" href="report_recipients.php">Manage Report Emails</a>
</div>

<?php if(isset($_GET["generated"])) echo "<div class='note'><strong>Report generated:</strong> Daily report has been created and added to report history. In a live server, this would be emailed automatically to active report recipients.</div>"; ?>

<div class="print-only"><h2>FreshGuard Supermarket Daily Report</h2><p>Generated by: <?= $_SESSION["name"] ?> | Date: <?= date("d M Y") ?></p></div>

<div class="grid grid-4">
<div class="card stat"><h3>Potential Waste Value</h3><strong>$<?= number_format($value,2) ?></strong></div>
<div class="card stat"><h3>Forecast Model</h3><strong>XGBoost</strong></div>
<div class="card stat"><h3>Products Need Discounts</h3><strong><?= $dp ?></strong></div>
<div class="card stat"><h3>Potential Savings</h3><strong>$<?= number_format($savings,2) ?></strong></div>
</div><br>

<div class="grid grid-2">
<div class="card">
<h2>Waste Risk Distribution</h2>
<div class="mini-chart">
<div class="mini-bar" style="height:<?= max(25,$counts["High"]*10) ?>px;background:#dc2626">High<br><?= $counts["High"] ?></div>
<div class="mini-bar" style="height:<?= max(25,$counts["Medium"]*10) ?>px;background:#f59e0b">Medium<br><?= $counts["Medium"] ?></div>
<div class="mini-bar" style="height:<?= max(25,$counts["Low"]*4) ?>px;background:#0f7a4f">Low<br><?= $counts["Low"] ?></div>
</div>
</div>

<div class="card">
<h2>Predicted Demand by Category</h2>
<div class="mini-chart">
<?php foreach($cat as $category=>$demand){ $h=max(25, min(170, round($demand/12))); echo "<div class='mini-bar' style='height:{$h}px;background:#2563eb'>{$category}<br>{$demand}</div>"; } ?>
</div>
</div>
</div><br>

<div class="grid grid-2">
<div class="card">
<h2>Report Email Recipients</h2><br>
<table><tr><th>Name</th><th>Email</th><th>Role</th><th>Frequency</th></tr>
<?php while($x=mysqli_fetch_assoc($rec)){ ?><tr><td><?= $x["recipient_name"] ?></td><td><?= $x["email"] ?></td><td><?= $x["role"] ?></td><td><?= $x["report_frequency"] ?></td></tr><?php } ?>
</table>
</div>

<div class="card">
<h2>Report History</h2><br>
<table><tr><th>Date</th><th>Type</th><th>Generated By</th><th>Status</th></tr>
<?php while($h=mysqli_fetch_assoc($history)){ ?><tr><td><?= $h["created_at"] ?></td><td><?= $h["report_type"] ?></td><td><?= $h["generated_by"] ?></td><td><?= $h["status"] ?></td></tr><?php } ?>
</table>
</div>
</div><br>

<div class="card">
<h2>Daily Report Summary</h2>
<p>The daily report identifies products with high expiry risk, medium risk inventory, potential waste value, suggested discount actions, forecast demand and category-level demand distribution. The report can be manually exported as PDF using the Export button, and recipients can be managed from the Report Emails page.</p>
</div>

</main></div></body></html>